import {
    startOfDay,
    endOfDay,
    subDays,
    addDays,
    endOfMonth,
    isSameDay,
    isSameMonth,
    addHours
} from 'date-fns';

export class CalendarEventDB {
    private colors: any = {
        red: {
            primary: '#f44336',
            secondary: '#FAE3E3'
        },
        blue: {
            primary: '#247ba0 ',
            secondary: '#D1E8FF'
        },
        yellow: {
            primary: '#ffd97d',
            secondary: '#FDF1BA'
        }
    };

    public events: any[] = [
        {
            _id: '100',
            start: addHours(startOfDay(new Date()), 19),
            time: '19:00',
            mainCast: 'まま',
            end: addHours(startOfDay(new Date()), 21),
            title: 'めぐみ 林様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            douhanCasts: 'めぐみ',
            note: '久兵衛で待ち合わせ。21時に同伴入店予定。',
            douhanCastsId: [1,2,3,4],
            color: this.colors.red,
            btn: 'danger'
        }, {
            _id: '101',
            start: addHours(startOfDay(new Date()), 19),
            time: '19:00',
            end: addHours(startOfDay(new Date()), 21),
            title: 'まい 山本様同伴',
            customer: '山本様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まい',
            douhanCasts: 'まい',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.blue,
            btn: 'info'
        }, {
            _id: '102',
            start: addHours(startOfDay(new Date()), 19),
            time: '20:00',
            end: addHours(startOfDay(new Date()), 21),
            title: 'まみ 田中様同伴',
            customer: '田中様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まみ',
            douhanCasts: 'まみ',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.red,
            btn: 'danger'
        }, {
            _id: '103',
            start: addHours(startOfDay(new Date()), 20),
            time: '20:00',
            end: addHours(startOfDay(new Date()), 22),
            title: 'みずき 吉田様同伴',
            customer: '吉田様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'みずき',
            douhanCasts: 'みずき',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.blue,
            btn: 'info',
            resizable: {
                beforeStart: true,
                afterEnd: true
            },
            draggable: true
        },
        {
            _id: '104',
            start: addHours(subDays(startOfDay(new Date()),1), 19),
            time: '20:30',
            end: addHours(subDays(startOfDay(new Date()),1), 21),
            title: 'みれい 小林様同伴',
            customer: '小林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'みれい',
            douhanCasts: 'みれい',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.red,
            btn: 'danger'
        }, {
            _id: '105',
            start: addHours(subDays(startOfDay(new Date()),2), 19),
            time: '20:30',
            end: addHours(subDays(startOfDay(new Date()),2), 21),
            title: 'みさ 山田様同伴',
            customer: '山田様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'みさ',
            douhanCasts: 'みさ',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.blue,
            btn: 'info'
        }, {
            _id: '106',
            start: addHours(subDays(startOfDay(new Date()),3), 19),
            time: '19:00',
            end: addHours(subDays(startOfDay(new Date()),3), 21),
            title: 'みゆき 田中様同伴',
            customer: '田中様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'みゆき',
            douhanCasts: 'みゆき',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.bule,
            btn: 'info'
        }, {
            _id: '107',
            start: addHours(subDays(startOfDay(new Date()),4), 19),
            time: '19:00',
            end: addHours(subDays(startOfDay(new Date()),4), 22),
            title: 'まり 吉田様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.blue,
            btn: 'info',
            resizable: {
                beforeStart: true,
                afterEnd: true
            },
            draggable: true
        },
        {
            _id: '110',
            start: addHours(startOfDay(new Date()), 19),
            time: '19:00',
            end: addHours(startOfDay(new Date()), 21),
            title: 'めぐみ 林様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.red,
            btn: 'danger'
        }, {
            _id: '111',
            start: addHours(startOfDay(new Date()), 19),
            time: '19:00',
            end: addHours(startOfDay(new Date()), 21),
            title: 'みなみ 山本様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.blue,
            btn: 'info'
        }, {
            _id: '112',
            start: addHours(startOfDay(new Date()), 19),
            time: '19:00',
            end: addHours(startOfDay(new Date()), 21),
            title: 'まみ 田中様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.red,
            btn: 'danger'
        }, {
            _id: '113',
            start: addHours(startOfDay(new Date()), 20),
            time: '19:00',
            end: addHours(startOfDay(new Date()), 22),
            title: 'みずき 吉田様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.blue,
            btn: 'info',
            resizable: {
                beforeStart: true,
                afterEnd: true
            },
            draggable: true
        },
        {
            _id: '120',
            start: addHours(subDays(startOfDay(new Date()),9), 19),
            time: '19:00',
            end: addHours(subDays(startOfDay(new Date()),9), 22),
            title: 'めぐみ 林様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '久兵衛で待ち合わせ。21時に同伴入店予定。',
            color: this.colors.red,
            btn: 'danger'
        }, {
            _id: '121',
            start: addHours(subDays(startOfDay(new Date()),9), 19),
            time: '19:00',
            end: addHours(subDays(startOfDay(new Date()),9), 22),
            title: 'みなみ 山本様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.blue,
            btn: 'info'
        }, {
            _id: '122',
            start: addHours(subDays(startOfDay(new Date()),9), 19),
            time: '19:00',
            end: addHours(subDays(startOfDay(new Date()),9), 22),
            title: 'まみ 田中様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.red,
            btn: 'danger'
        }, {
            _id: '123',
            start: addHours(subDays(startOfDay(new Date()),9), 19),
            time: '19:00',
            end: addHours(subDays(startOfDay(new Date()),9), 22),
            title: 'みずき 吉田様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.blue,
            btn: 'info',
            resizable: {
                beforeStart: true,
                afterEnd: true
            },
            draggable: true
        },
        {
            _id: '124',
            start: addHours(subDays(startOfDay(new Date()),9), 19),
            time: '19:00',
            end: addHours(subDays(startOfDay(new Date()),9), 22),
            title: 'みれい 林様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.red,
            btn: 'danger'
        }, {
            _id: '125',
            start: addHours(subDays(startOfDay(new Date()),9), 19),
            time: '19:00',
            end: addHours(subDays(startOfDay(new Date()),9), 22),
            title: 'みさ 山本様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.blue,
            btn: 'info'
        }, {
            _id: '126',
            start: addHours(subDays(startOfDay(new Date()),9), 19),
            time: '19:00',
            end: addHours(subDays(startOfDay(new Date()),9), 22),
            title: 'みゆき 田中様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.bule,
            btn: 'info'
        }, {
            _id: '127',
            start: addHours(subDays(startOfDay(new Date()),9), 19),
            time: '19:00',
            end: addHours(subDays(startOfDay(new Date()),9), 22),
            title: 'まり 吉田様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.blue,
            btn: 'info',
            resizable: {
                beforeStart: true,
                afterEnd: true
            },
            draggable: true
        },
        {
            _id: '120',
            start: addHours(subDays(startOfDay(new Date()),9), 19),
            time: '19:00',
            end: addHours(subDays(startOfDay(new Date()),9), 22),
            title: 'めぐみ 林様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.red,
            btn: 'danger'
        }, {
            _id: '121',
            start: addHours(subDays(startOfDay(new Date()),9), 19),
            time: '19:00',
            end: addHours(subDays(startOfDay(new Date()),9), 22),
            title: 'みなみ 山本様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.blue,
            btn: 'info'
        }, {
            _id: '122',
            start: addHours(subDays(startOfDay(new Date()),9), 19),
            time: '19:00',
            end: addHours(subDays(startOfDay(new Date()),9), 22),
            title: 'まみ 田中様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.red,
            btn: 'danger'
        }, {
            _id: '123',
            start: addHours(subDays(startOfDay(new Date()),9), 19),
            time: '19:00',
            end: addHours(subDays(startOfDay(new Date()),9), 22),
            title: 'みずき 吉田様同伴',
            customer: '林様',
            customerId: 1,
            numberOfCustomer: 5,
            mainCast: 'まま',
            douhanCasts: 'めい、みか、みさと',
            douhanCastsId: [1,2,3,4],
            note: '',
            color: this.colors.blue,
            btn: 'info',
            resizable: {
                beforeStart: true,
                afterEnd: true
            },
            draggable: true
        },
    ];
}
